export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
};

export const Items = [{
        id: 1,
        category: 'product',
        productName: 'True Wireless Sony WF-C500 Earphones',
        productPrice: 1799,
        description: 'Discover the freedom of Bluetooth connectivity with the compact WF-C500 truly wireless earbuds, combining uncompromising sound with great battery life, personalization, and IPX4 water resistance for music that goes anywhere.',
        isOff: true,
        offPercentage: 10,
        productImage: require('./images/Tai nghe True Wireless Sony WF-C500/4174_tai_nghe_true_wireless_sony_wf_c500_chinh_hang_gia_re_1.jpg'),
        isAvailable: true,
        productImageList: [
            require('./images/Tai nghe True Wireless Sony WF-C500/4174_tai_nghe_true_wireless_sony_wf_c500_chinh_hang_gia_re_1.jpg'),
            require('./images/Tai nghe True Wireless Sony WF-C500/4174_tai_nghe_true_wireless_sony_wf_c500_chinh_hang_gia_re_2.jpg'),
            require('./images/Tai nghe True Wireless Sony WF-C500/4174_tai_nghe_true_wireless_sony_wf_c500_chinh_hang_gia_re_3.jpg'),
        ],
    },
    {
        id: 2,
        category: 'product',
        productName: 'Campfire Ara Earphones',
        productPrice: 1499,
        description: 'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
        isOff: false,
        productImage: require('./images/Tai nghe Campfire Ara/Tai nghe Campfire Ara.jpg'),
        isAvailable: true,
        productImageList: [
            require('./images/Tai nghe Campfire Ara/Tai nghe Campfire Ara.jpg'),
            require('./images/Tai nghe Campfire Ara/2984_ara_1_ws.jpg'),
            require('./images/Tai nghe Campfire Ara/2984_ara_2_ws.jpg'),
        ],
    },
    {
        id: 3,
        category: 'accessory',
        productName: 'Campfire Andromeda 2020 Earphones',
        productPrice: 1999,
        description: 'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
        isOff: true,
        offPercentage: 18,
        productImage: require('./images/Tai nghe Campfire Andromeda 2020/Tai nghe Campfire Andromeda 2020.jpg'),
        isAvailable: true,
        productImageList: [
            require('./images/Tai nghe Campfire Andromeda 2020/Tai nghe Campfire Andromeda 2020.jpg'),
        ],
    },
    {
        id: 4,
        category: 'accessory',
        productName: 'Bluetooth Marshall Major IV Headphone',
        productPrice: 399,
        description: 'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
        isOff: false,
        productImage: require('./images/Tai nghe Bluetooth Marshall Major IV/Tai nghe Bluetooth Marshall Major IV.jpg'),
        isAvailable: true,
        productImageList: [
            require('./images/Tai nghe Bluetooth Marshall Major IV/Tai nghe Bluetooth Marshall Major IV.jpg'),
            require('./images/Tai nghe Bluetooth Marshall Major IV/3560_marshall_major_iv_black_e1601535769509.jpg'),
        ],
    },
    {
        id: 5,
        category: 'accessory',
        productName: 'Apple Airpods Pro',
        productPrice: 1499,
        description: 'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
        isOff: false,
        productImage: require('./images/Tai nghe không dây Apple Airpods Pro/Tai nghe không dây Apple Airpods Pro.jpg'),
        isAvailable: false,
        productImageList: [
            require('./images/Tai nghe không dây Apple Airpods Pro/Tai nghe không dây Apple Airpods Pro.jpg'),
            require('./images/Tai nghe không dây Apple Airpods Pro/3380_2571_mwp22_av1.jpg'),
            require('./images/Tai nghe không dây Apple Airpods Pro/3380_2571_mwp22_av2.jpg'),
        ],
    },
    {
        id: 6,
        category: 'accessory',
        productName: 'Skullcandy Crusher ANC Headphone',
        productPrice: 1299,
        description: 'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
        isOff: false,
        productImage: require('./images/Tai nghe Skullcandy Crusher ANC/Tai nghe Skullcandy Crusher ANC.jpg'),
        isAvailable: true,
        productImageList: [
            require('./images/Tai nghe Skullcandy Crusher ANC/Tai nghe Skullcandy Crusher ANC.jpg'),
            require('./images/Tai nghe Skullcandy Crusher ANC/2675_tai_nghe_skullcandy_crusher_anc_chinh_hang_1.jpg'),
        ],
    },
];